
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-weather
spec:
  selector:
    matchLabels:
      app: hello-weather
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-weather
    spec:
      containers:
      - name: hello-weather
        image: johnny-urkens/bpoefening:latest
        ports:
        - containerPort: 80